### ISSUE TITLE
Examples crash when trying to open in Safari

### ISSUE THREAD

**Issue by booyaa** [steveklabnik/simple-server#68] opened 2017-10-17 06:30 UTC
Works fine in FireFox (including Nightly) and Chrome.

Versions:
- OS: MacOS High Sierra
- Safari: Version 11.0 (12604.1.38.1.7)
- Kernel: Darwin hodor.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
- rustc 1.21.0 (3b72af97e 2017-10-09)
- cargo 0.22.0 (3423351a5 2017-10-06)
- rustup 1.6.0 (a11c01e8c 2017-08-30)

```
 $ RUST_BACKTRACE=1 cargo run --example server
   Compiling simple-server v0.1.0 (file:///Users/booyaa/Dev/rust/clowns/simple-server)
    Finished dev [unoptimized + debuginfo] target(s) in 3.57 secs
     Running `target/debug/examples/server`
thread '<unnamed>' panicked at 'Tried to unwrap Status::Partial', /Users/booyaa/.cargo/registry/src/github.com-1ecc6299db9ec823/httparse-1.2.3/src/lib.rs:254:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: <httparse::Status<T>>::unwrap
   6: simple_server::parse_request
   7: simple_server::Server::handle_connection
   8: simple_server::Server::listen::{{closure}}::{{closure}}
   9: <F as scoped_threadpool::FnBox>::call_box
  10: scoped_threadpool::Pool::new::{{closure}}
thread 'main' panicked at 'Thread pool worker panicked', /Users/booyaa/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:236:12
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: scoped_threadpool::Scope::join_all
   6: <scoped_threadpool::Scope<'pool, 'scope> as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place
   8: scoped_threadpool::Pool::scoped
   9: simple_server::Server::listen
  10: server::main
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
  13: main
```

**Comment by ashleygwilliams** [comment] 2017-10-17 14:45
hey @booyaa ! thanks for filing. i just tried to reproduce this on my machine (same except i'm not on High Sierra) and could not. i'm gonna tag this with `needs reproduction` and see if we cant get someone else to reproduce it so we can get to fixing it!

if you happen to figure it out please follow up on this thread!

**Comment by urschrei** [comment] 2017-10-17 15:04
Can't repro on High Sierra:

- Safari Version 11.0 (13604.1.38.1.6)
- rustc 1.21.0 (3b72af97e 2017-10-09)
- System Version: macOS 10.13 (17A365)
- Kernel Version: Darwin 17.0.0

**Comment by aaroncm** [comment] 2017-10-17 15:12
Can't repro here either.

- Commit 66d8b4d
- rustc 1.21.0 (3b72af97e 2017-10-09)
- Safari Version 11.0 (13604.1.38.1.6)
- Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

**Comment by mgattozzi** [comment] 2017-10-17 15:20
It looks like @urschrei and @aaroncm are using a newer version of Safari. @booyaa maybe if you update Safari it'll solve your problem?

**Comment by lewiscowper** [comment] 2017-10-17 15:27
Hello all,

I'm running the following versions of things, and can report no crash here. 😢

<img width="465" alt="screen shot 2017-10-17 at 17 24 53" src="https://user-images.githubusercontent.com/593574/31673704-384fe5ae-b360-11e7-8a86-f1b3eb3fb808.png">

<details>
<summary>Version info</summary>
<ul>
<li>MacOS: High Sierra 10.13.1 Beta (17B35a)</li>
<li>Safari: 11.0.1 (13604.3.4)</li>
<li>Kernel: Darwin Kernel Version 17.2.0: Sun Oct  1 00:46:50 PDT 2017; root:xnu-4570.20.62~10/RELEASE_X86_64 x86_64</li>
<li>Rustc: 1.21.0 (3b72af97e 2017-10-09)</li>
<li>Cargo: 0.22.0 (3423351a5 2017-10-06)</li>
<li>Rustup: 1.6.0 (a11c01e8c 2017-08-30)</li>
</ul>
</details>

**Comment by mistydemeo** [comment] 2017-10-17 15:47
I can't repro on High Sierra either.

Commit 66d8b4d
rustc 1.21.0
Safari Version 11.0 (13604.1.38.1.6)
Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

**Comment by Sadin** [comment] 2017-10-17 15:54
Cant reproduce either. 

- rustc 1.21.0 (3b72af97e 2017-10-09)
- Safari Version 11.0 (13604.1.38.1.6)
- Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64

**Comment by booyaa** [comment] 2017-10-17 16:23
This is definitely looking like a fault with this Safari build (12604.1.38.1.7). 

Thanks everyone! 

If anyone has a suggestion how I might catch what Safari is trying to send in the request to simple_server, would greatly appreciate it.

**Comment by gmbeard** [comment] 2017-10-17 18:04
@booyaa Your stack trace output gives it away. The current request handling code is a little naive and each request cannot exceed 512 bytes, including headers. If it does, then it `unwrap()`s a `Partial` content response, which panics. 

To demonstrate, you can replicate this using CURL...

```
curl --header "X-SOME-HEADER: gWbWykBHgObDHriErqIKRBqebBekBpHsqUJqQcDtDctkaeeFBwNelgvzigaEkUPKAfcnYGhgbzDOvGumdewDzCqOantKfsvaZuggZaTjqtUzOXHVYwsSjknsMTPyWzvzGrNdRExaSIjiehYvuSAMdOMpwakKlKxCPwYAyAlpqXpoiargAZnAVIRfUJVpBnotmQRsDtAZoFfSXyRvqGQluzWWVTOCItNSCqBPUfFQGoxoSewvuSStgDtCYfCnFCFNczEwGkLiPidmrpbQDPuIvopUbxvojuUrBfgjoTwslrnDIJGAWIMoMkOQzYdzxVaCDfSQlmHwkpdkxByhuWXmuLgAzgJvIuhAMMlXaHIMcGmymGCxsgUjUkzKwrzafCsfkSivOXIzNSmTGhdgBufQTqdlRbuDBZijZCOXmpwhKFzlaSleXzgMaEpDiEjxzPUwIOwhomPDVSzaTqEZCpivNWyfunffMNUaLdkxLudYEpSgwTOGUipJjvXbocrKbfFG" http://127.0.0.1:7878
```

The fact that noone seems to have this problem points to your individual browser configuration. It maybe that you've used one or more previous HTTP servers on`127.0.0.1`, and your cookie cache for this address contains a lot of cookies (well, enough to push the request size over 512 bytes). AFAIK, all these previous cookies (which haven't expired) will be sent to the example here. Try opening the example in Private Mode to see if that solves it.

**Comment by booyaa** [comment] 2017-10-17 19:21
Wow thanks @gmbeard switched to private and it didn't crash the `server` example! Time to go clear out the cookies for 127.0.0.1. Nice detective work!

**Comment by booyaa** [comment] 2017-10-17 19:23
Time to write a test to reproduce it, so I can have a go fixing it! 😄

**Comment by steveklabnik** [comment] 2017-10-17 20:56
> It maybe that you've used one or more previous HTTP servers on127.0.0.1, and your cookie cache for this address contains a lot of cookies (well, enough to push the request size over 512 bytes). AFAIK, all these previous cookies (which haven't expired) will be sent to the example here. 

That is amazing! Like a lightbulb. Great job debugging!

This means this is a duplicate of https://github.com/steveklabnik/simple-server/issues/19

**Closed by steveklabnik** 2017-10-17 20:56 UTC
Labels: needs reproduction
